#!/usr/bin/env Rscript
# Generate R wrapper functions from JSON specs
#
# Usage: Rscript tools/gen_wrappers.R
#
# Reads all inst/specs/*.json and generates R/wrappers_auto.R

library(jsonlite)

spec_dir <- "inst/specs"
output_file <- "R/wrappers_auto.R"

spec_files <- list.files(spec_dir, pattern = "\\.json$", full.names = TRUE)

# Map spec type to R default value representation
type_default <- function(def) {
  if (!is.null(def$default)) {
    val <- def$default
    if (is.character(val)) return(paste0('"', val, '"'))
    if (is.logical(val)) return(if (val) "TRUE" else "FALSE")
    return(as.character(val))
  }
  "NULL"
}

# Map spec type to R @param type description
type_desc <- function(def) {
  base <- switch(def$type,
    file = "Character; file path",
    dir = "Character; directory path",
    string = "Character",
    int = "Integer",
    double = "Numeric",
    bool = "Logical",
    flag = "Logical",
    enum = paste0("Character; one of: ", paste0('"', def$choices, '"', collapse = ", ")),
    list = "Character or numeric vector",
    "Character"
  )
  if (!is.null(def$desc)) {
    # Escape special roxygen2 characters in Nipype descriptions
    desc <- gsub("\\{", "\\\\{", def$desc)
    desc <- gsub("\\}", "\\\\}", desc)
    desc <- gsub("\\[", "\\\\[", desc)
    desc <- gsub("\\]", "\\\\]", desc)
    paste0(base, ". ", desc)
  } else {
    base
  }
}

# Convert spec id to R function name: fsl.bet -> ni_fsl_bet
spec_id_to_func <- function(id) {
  paste0("ni_", gsub("\\.", "_", id))
}

# Generate one wrapper function
gen_wrapper <- function(spec_path) {
  spec <- fromJSON(spec_path, simplifyVector = TRUE, simplifyDataFrame = FALSE)

  func_name <- spec_id_to_func(spec$id)
  inputs <- spec$inputs

  # Separate required and optional params
  req_names <- character(0)
  opt_names <- character(0)
  for (nm in names(inputs)) {
    if (isTRUE(inputs[[nm]]$required)) {
      req_names <- c(req_names, nm)
    } else {
      opt_names <- c(opt_names, nm)
    }
  }

  # Build function signature
  params <- character(0)
  for (nm in req_names) {
    params <- c(params, nm)
  }
  for (nm in opt_names) {
    def <- inputs[[nm]]
    params <- c(params, paste0(nm, " = ", type_default(def)))
  }
  params <- c(params, ".cwd = NULL", ".env = NULL", ".container = NULL",
              "dry_run = FALSE", "echo = interactive()")
  sig <- paste(params, collapse = ",\n                     ")

  # Build roxygen
  roxy <- character(0)
  roxy <- c(roxy, paste0("#' ", spec$title))
  roxy <- c(roxy, "#'")
  if (!is.null(spec$description)) {
    roxy <- c(roxy, paste0("#' ", spec$description))
    roxy <- c(roxy, "#'")
  }
  for (nm in c(req_names, opt_names)) {
    def <- inputs[[nm]]
    tag <- if (isTRUE(def$required)) " **Required.**" else ""
    roxy <- c(roxy, paste0("#' @param ", nm, " ", type_desc(def), tag))
  }
  roxy <- c(roxy, "#' @param .cwd Working directory override.")
  roxy <- c(roxy, "#' @param .env Named character vector of environment variables.")
  roxy <- c(roxy, "#' @param .container Container configuration list.")
  roxy <- c(roxy, "#' @param dry_run Logical; preview command without executing.")
  roxy <- c(roxy, "#' @param echo Logical; echo stdout/stderr in real time.")
  roxy <- c(roxy, "#' @return An `ni_result` object.")
  roxy <- c(roxy, "#' @export")

  # Build the argument-forwarding call
  all_names <- c(req_names, opt_names)
  fwd <- paste(paste0(all_names, " = ", all_names), collapse = ", ")

  # Assemble function body
  lines <- c(
    paste(roxy, collapse = "\n"),
    paste0(func_name, " <- function(", sig, ") {"),
    paste0('  call <- ni_call("', spec$id, '", ', fwd,
           ", .cwd = .cwd, .env = .env, .container = .container)"),
    "  ni_run(call, dry_run = dry_run, echo = echo)",
    "}"
  )

  paste(lines, collapse = "\n")
}

# Generate all wrappers
cat("Generating wrappers from", length(spec_files), "specs...\n")

header <- paste0(
  "# Auto-generated wrapper functions — do not edit by hand\n",
  "# Generated by tools/gen_wrappers.R on ", Sys.Date(), "\n",
  "# Regenerate with: Rscript tools/gen_wrappers.R\n",
  "\n"
)

bodies <- vapply(spec_files, gen_wrapper, character(1))
content <- paste0(header, paste(bodies, collapse = "\n\n"), "\n")

writeLines(content, output_file)
cat("Wrote", output_file, "\n")
